'use strict';
// Patch feature gates — computes globalThis.__clawgodPatches before the
// patched cli loads. Config: user-edited ~/.clawgod/patches.json
// ({"<feature>": false}, absent key = on). Per-feature env overrides for a
// single launch: CLAWGOD_FEATURE_<NAME>=false (feature id upper-cased,
// dashes → underscores, e.g. CLAWGOD_FEATURE_GEO_NEUTRALIZE=false; "true"
// restores a feature disabled in patches.json). CLAWGOD_FEATURES_META
// below is machine-generated by build.js from the FEATURES registry in
// patch.mjs (single source of truth) — do not hand-edit. Each gated patch in
// cli.original.cjs checks its own entry:
//   globalThis.__clawgodPatches?.["<patchId>"] !== false
// Missing config defaults all gates ON. Invalid configuration stops startup.
// {{CLAWGOD:FEATURES_META}}

var clawgodDir = __dirname;

var _cfg = {};
try {
  _cfg = JSON.parse(require('fs').readFileSync(require('path').join(clawgodDir, 'patches.json'), 'utf8').replace(/^\uFEFF/, ''));
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}
if (!_cfg || typeof _cfg !== 'object' || Array.isArray(_cfg)) throw new Error('patches.json must contain a feature object');
if (Object.hasOwn(_cfg, 'enabled')) throw new Error('Legacy patches.json: rerun the ClawGod installer to migrate capability settings');
for (var _name in process.env) {
  if (_name.indexOf('CLAWGOD_FEATURE_') !== 0) continue;
  var _val = process.env[_name];
  if (_val !== 'true' && _val !== 'false') continue;
  _cfg[_name.slice('CLAWGOD_FEATURE_'.length).toLowerCase().replace(/_/g, '-')] = _val === 'true';
}

// META keys are patch/runtime ids; their values name the known features.
// Unknown keys are residue (renamed/removed features).
for (var _k in _cfg) {
  var _known = false;
  for (var _f in CLAWGOD_FEATURES_META) {
    if (CLAWGOD_FEATURES_META[_f].indexOf(_k) >= 0) { _known = true; break; }
  }
  if (!_known) process.stderr.write('[clawgod] warning: unknown feature "' + _k + '" in patches.json\n');
}

var _gate = {};
for (var _pid in CLAWGOD_FEATURES_META) {
  var _feats = CLAWGOD_FEATURES_META[_pid];
  var _on = false;
  for (var _j = 0; _j < _feats.length; _j++) {
    if (_cfg[_feats[_j]] !== false) { _on = true; break; }
  }
  _gate[_pid] = _on;
}
globalThis.__clawgodPatches = _gate;

module.exports.isEnabled = function (feature) { return _cfg[feature] !== false; };
if (require.main === module && process.argv[2] === '--enabled') {
  if (!Object.values(CLAWGOD_FEATURES_META).some(function (features) { return features.includes(process.argv[3]); })) {
    throw new Error('Unknown feature: ' + process.argv[3]);
  }
  process.stdout.write(module.exports.isEnabled(process.argv[3]) ? '1\n' : '0\n');
}
