'use strict';
// Patch feature gates — computes globalThis.__clawgodPatches before the
// patched cli loads. Config: user-edited ~/.clawgod/patches.json
// ({"<feature>": false}, absent key = on). Per-feature env overrides for a
// single launch: CLAWGOD_FEATURE_<NAME>=false (feature id upper-cased,
// dashes → underscores, e.g. CLAWGOD_FEATURE_GEO_NEUTRALIZE=false; "true"
// restores a feature disabled in patches.json). CLAWGOD_FEATURES_META
// below is machine-generated by build.js from the FEATURES registry in
// patch.mjs (single source of truth) — do not hand-edit. Each gated patch in
// cli.original.cjs checks its own entry:
//   globalThis.__clawgodPatches?.["<patchId>"] !== false
// Missing config defaults all gates ON. Invalid configuration stops startup.
// {{CLAWGOD:FEATURES_META}}

var clawgodDir = __dirname;
var configFile = require('path').join(clawgodDir, 'patches.json');
var configText;

var _cfg = {};
try {
  configText = require('fs').readFileSync(configFile, 'utf8');
  _cfg = JSON.parse(configText.replace(/^\uFEFF/, ''));
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}
if (!_cfg || typeof _cfg !== 'object' || Array.isArray(_cfg)) throw new Error('patches.json must contain a feature object');
if (require.main === module && ['--check', '--enabled', '--migrate'].includes(process.argv[2]) && Object.hasOwn(_cfg, 'enabled')) {
  var legacy = {
    'clawgod.features-config': ['features-config'],
    'clawgod.green-theme': ['theme'],
    'clawgod.lean-settings': ['lean-settings'],
    'clawgod.provider-config': ['provider-config'],
    'clawgod.update-command-redirect': ['update-command-redirect'],
    'clawgod.update-notification': ['update-notification'],
    'features.agent-teams': ['agent-teams'],
    'features.anthropic-user-type': ['anthropic-user-type', 'message-filter'],
    'features.auto-mode': ['auto-mode'],
    'features.computer-use': ['computer-use'],
    'features.custom-model-aliases': ['custom-model-aliases'],
    'features.hide-login-notice': ['not-logged-in'],
    'features.ultraplan': ['ultraplan'],
    'features.ultrareview': ['ultrareview'],
    'features.voice-mode': ['voice-mode'],
    'fixes.hook-update-agent-model': ['hook-update-agent-model'],
    'fixes.macos-image-paste': ['macos-image-paste'],
    'fixes.send-message-resume-model': ['send-message-resume-model'],
    'system-prompt.remove-attribution-header': ['remove-attribution-header'],
    'system-prompt.remove-cautious-actions': ['cautious-actions'],
    'system-prompt.remove-cyber-risk-instruction': ['cyber-risk'],
    'system-prompt.remove-geo-steganography': ['geo-neutralize'],
    'system-prompt.remove-url-generation-restriction': ['url-restriction'],
  };
  if (!Array.isArray(_cfg.enabled) || _cfg.enabled.some(function (id) { return typeof id !== 'string'; })) {
    throw new Error('Legacy patches.json must contain an enabled string array');
  }
  var unknown = _cfg.enabled.filter(function (id) { return !Object.hasOwn(legacy, id); });
  var extra = Object.keys(_cfg).filter(function (key) { return key !== 'enabled'; });
  if (unknown.length || extra.length) throw new Error('Cannot migrate unknown capabilities or fields: ' + unknown.concat(extra).join(', '));
  var selected = new Set(_cfg.enabled);
  var converted = {};
  for (var oldId in legacy) {
    for (var feature of legacy[oldId]) converted[feature] = selected.has(oldId);
  }
  if (process.argv[2] === '--migrate') {
    var fs = require('fs');
    var suffix = Date.now() + '-' + process.pid;
    var backup = configFile + '.legacy-' + suffix + '.bak';
    var temporary = configFile + '.tmp-' + suffix;
    fs.writeFileSync(backup, configText, {flag:'wx', mode:0o600});
    fs.writeFileSync(temporary, JSON.stringify(converted, null, 2) + '\n', {flag:'wx', mode:0o600});
    try { fs.renameSync(temporary, configFile); }
    catch (error) { fs.unlinkSync(temporary); throw error; }
    process.stdout.write('[clawgod] Migrated legacy capabilities; backup: ' + backup + '\n');
  }
  _cfg = converted;
}
if (Object.hasOwn(_cfg, 'enabled')) throw new Error('Legacy patches.json: rerun the ClawGod installer to migrate capability settings');
for (var _name in process.env) {
  if (_name.indexOf('CLAWGOD_FEATURE_') !== 0) continue;
  var _val = process.env[_name];
  if (_val !== 'true' && _val !== 'false') continue;
  _cfg[_name.slice('CLAWGOD_FEATURE_'.length).toLowerCase().replace(/_/g, '-')] = _val === 'true';
}

// META keys are patch/runtime ids; their values name the known features.
// Unknown keys are residue (renamed/removed features).
for (var _k in _cfg) {
  var _known = false;
  for (var _f in CLAWGOD_FEATURES_META) {
    if (CLAWGOD_FEATURES_META[_f].indexOf(_k) >= 0) { _known = true; break; }
  }
  if (!_known) process.stderr.write('[clawgod] warning: unknown feature "' + _k + '" in patches.json\n');
}

var _gate = {};
for (var _pid in CLAWGOD_FEATURES_META) {
  var _feats = CLAWGOD_FEATURES_META[_pid];
  var _on = false;
  for (var _j = 0; _j < _feats.length; _j++) {
    if (_cfg[_feats[_j]] !== false) { _on = true; break; }
  }
  _gate[_pid] = _on;
}
globalThis.__clawgodPatches = _gate;

module.exports.isEnabled = function (feature) { return _cfg[feature] !== false; };
if (require.main === module && process.argv[2] === '--enabled') {
  if (!Object.values(CLAWGOD_FEATURES_META).some(function (features) { return features.includes(process.argv[3]); })) {
    throw new Error('Unknown feature: ' + process.argv[3]);
  }
  process.stdout.write(module.exports.isEnabled(process.argv[3]) ? '1\n' : '0\n');
}
